import { ComponentEntity } from '@/types';

export const COMPONENTS_CATALOG: ComponentEntity[] = [
  {
    id: 'navbar',
    slug: 'navbar',
    name: 'Responsive Header & Navigation Bar',
    category: 'Navigation',
    description:
      'Komponen navigasi primer sticky dengan logo institusi, tautan halaman berhierarki jelas, penanda bahasa (ID/EN), dan tombol call-to-action konversi utama.',
    bestPractices: [
      'Gunakan semantic tag <header> dan <nav aria-label="Main Navigation">',
      'Pastikan tombol menu mobile memiliki atribut aria-expanded dan aria-controls',
      'Hindari tautan menu bertingkat lebih dari 2 level di tampilan smartphone',
      'Terapkan efek backdrop-blur saat navigasi bergulir agar konten di bawahnya tetap terbaca',
    ],
    useCases: [
      'Navigasi utama di seluruh halaman website platform',
      'Akses instan ke katalog desain dan simulasi harga',
      'Navigasi cepat ke formulir kontak dan chat WhatsApp',
    ],
    compatibleWebsiteTypes: ['company-profile', 'landing-page', 'ecommerce', 'restaurant', 'hotel', 'school', 'portfolio', 'service-business', 'custom'],
    compatibleIndustries: ['construction', 'law-firm', 'accounting', 'technology', 'healthcare'],
    relatedDesigns: ['modern-corporate', 'minimal-business', 'technology'],
    seoTitle: 'Komponen Responsive Navbar & Header Web Profesional',
    seoDescription: 'Panduan dan arsitektur komponen navigasi header responsif dengan menu mobile ramah aksesibilitas dan CTA terarah.',
    keyUXConsiderations: 'Pertahankan posisi sticky dan kontras warna yang cukup agar pengunjung selalu memiliki kendali navigasi di mana pun mereka berada.',
  },
  {
    id: 'mega-menu',
    slug: 'mega-menu',
    name: 'Accessible Enterprise Mega Menu',
    category: 'Navigation',
    description:
      'Panel navigasi multi-kolom yang mengelompokkan puluhan kategori layanan, artikel panduan, dan sub-sektor industri ke dalam grid terorganisir tanpa membuat pengguna kewalahan.',
    bestPractices: [
      'Dukungan penuh navigasi keyboard (Tab, Escape, Arrow keys)',
      'Kelompokkan tautan berdasarkan kategori logis dengan judul tebal',
      'Sertakan kartu promosi visual ringkas di kolom paling kanan mega menu',
    ],
    useCases: [
      'Portal korporat skala besar dengan banyak divisi bisnis',
      'Website universitas dengan puluhan fakultas dan program studi',
      'Toko e-commerce multi-kategori barang',
    ],
    compatibleWebsiteTypes: ['company-profile', 'school', 'custom', 'ecommerce'],
    compatibleIndustries: ['university', 'manufacturing', 'retail', 'logistics'],
    relatedDesigns: ['modern-corporate', 'industrial'],
    seoTitle: 'Komponen Mega Menu Multi-Kolom Enterprise',
    seoDescription: 'Arsitektur komponen mega menu berstandar aksesibilitas tinggi untuk navigasi situs web besar berstruktur kompleks.',
    keyUXConsiderations: 'Berikan jeda waktu penutupan (debounce) halus saat kursor berpindah agar menu tidak tertutup secara tidak sengaja.',
  },
  {
    id: 'hero',
    slug: 'hero',
    name: 'High-Impact Hero Section',
    category: 'Hero & Headers',
    description:
      'Area layar pertama (above-the-fold) dengan proposisi nilai utama, headline yang menggugah, sub-judul penjelasan, tombol aksi ganda (primary & secondary CTA), dan badge kepercayaan.',
    bestPractices: [
      'Gunakan tag <h1> tunggal yang jelas mengandung maksud pencarian utama',
      'Optimalkan Largest Contentful Paint (LCP) dengan memprioritaskan aset gambar hero',
      'Hindari slider otomatis bergerak yang membingungkan fokus membaca pengguna',
    ],
    useCases: [
      'Halaman beranda utama website',
      'Bagian paling atas pada landing page kampanye iklan berbayar',
      'Halaman perkenalan kategori industri khusus',
    ],
    compatibleWebsiteTypes: ['company-profile', 'landing-page', 'service-business', 'portfolio'],
    compatibleIndustries: ['construction', 'consultant', 'law-firm', 'technology', 'saas'],
    relatedDesigns: ['bold-creative', 'modern-corporate', 'premium-corporate'],
    seoTitle: 'Komponen Hero Section Berkonversi Tinggi & Cepat Muat',
    seoDescription: 'Desain hero section website profesional yang mengomunikasikan proposisi nilai dalam 3 detik pertama kunjungan.',
    keyUXConsiderations: 'Pastikan kontras teks terhadap latar belakang memenuhi standar WCAG AAA agar mudah dibaca di layar ponsel di bawah sinar matahari.',
  },
  {
    id: 'cta',
    slug: 'cta',
    name: 'Conversion Call-to-Action Banner',
    category: 'Conversion & CTA',
    description:
      'Blok penutup strategis yang merangkum urgensi penawaran, jaminan kemudahan proses, dan mengarahkan pengguna untuk mengambil keputusan tindakan (action).',
    bestPractices: [
      'Gunakan teks tombol yang berorientasi hasil spesifik (cth: "Bangun Website Anda" bukan "Kirim")',
      'Sertakan mikro-komitmen bebas risiko (cth: "Tanpa komitmen &bull; Respon cepat jam kerja")',
      'Beri ruang kosong (padding) yang lapang agar blok terlihat menonjol',
    ],
    useCases: [
      'Bagian penutup sebelum footer di setiap halaman komersial',
      'Banner transisi di antara pembahasan artikel studi kasus',
    ],
    compatibleWebsiteTypes: ['company-profile', 'landing-page', 'service-business', 'custom'],
    compatibleIndustries: ['consultant', 'property', 'contractor', 'software'],
    relatedDesigns: ['modern-corporate', 'bold-creative'],
    seoTitle: 'Komponen Call-to-Action (CTA) Berorientasi Konversi',
    seoDescription: 'Strategi perancangan tombol dan banner Call-to-Action untuk mendongkrak persentase konversi prospek website.',
    keyUXConsiderations: 'Jadikan tombol cukup besar untuk disentuh dengan mudah pada layar sentuh smartphone (minimal area sentuh 48x48 pixel).',
  },
  {
    id: 'pricing-card',
    slug: 'pricing-card',
    name: 'Transparent Pricing Matrix Card',
    category: 'Pricing & Commerce',
    description:
      'Kartu perbandingan paket harga yang menampilkan nama tier, banderol biaya terformat, daftar fitur tercakup, durasi estimasi pengerjaan, dan tombol pilihan paket.',
    bestPractices: [
      'Sorot satu tier paling populer secara visual dengan outline khusus atau badge rekomendasi',
      'Gunakan icon centang hijau jelas untuk fitur yang disertakan',
      'Tampilkan nominal harga secara transparan tanpa embel-embel biaya tersembunyi',
    ],
    useCases: [
      'Halaman paket website resmi (/website-packages)',
      'Halaman penawaran paket jasa langganan SaaS',
    ],
    compatibleWebsiteTypes: ['service-business', 'custom', 'company-profile'],
    compatibleIndustries: ['saas', 'software', 'accounting', 'training'],
    relatedDesigns: ['modern-corporate', 'technology', 'minimal-business'],
    seoTitle: 'Komponen Kartu Harga & Matriks Paket Transparan',
    seoDescription: 'Struktur kartu harga modern yang memudahkan calon pelanggan membandingkan deliverables setiap paket investasi.',
    keyUXConsiderations: 'Kelompokkan fitur yang disertakan dari yang paling esensial hingga nilai tambah agar perbandingan logis.',
  },
  {
    id: 'feature-grid',
    slug: 'feature-grid',
    name: 'Modular Feature & Capability Grid',
    category: 'Content & Layout',
    description:
      'Susunan grid 3 atau 4 kolom berisi icon fungsional, judul fitur tegas, dan deskripsi manfaat ringkas untuk menjelaskan kapabilitas sistem atau layanan.',
    bestPractices: [
      'Batasi deskripsi per fitur maksimal 2 hingga 3 baris agar ritme visual seimbang',
      'Gunakan icon vektor SVG yang konsisten dalam satu keluarga gaya desain',
      'Terapkan efek hover halus pada kartu untuk memberikan umpan balik interaksi',
    ],
    useCases: [
      'Penjelasan fitur teknologi pada website SaaS',
      'Pameran keunggulan fasilitas pada website hotel atau sekolah',
    ],
    compatibleWebsiteTypes: ['company-profile', 'landing-page', 'school', 'custom'],
    compatibleIndustries: ['technology', 'saas', 'hotel', 'manufacturing'],
    relatedDesigns: ['technology', 'modern-corporate'],
    seoTitle: 'Komponen Grid Fitur & Keunggulan Layanan Modular',
    seoDescription: 'Tata letak grid fitur responsif untuk mengomunikasikan kapabilitas sistem dan nilai jual unik secara terstruktur.',
    keyUXConsiderations: 'Pada layar mobile kecil, otomatis ubah grid menjadi 1 kolom yang nyaman dibaca tanpa terpotong.',
  },
  {
    id: 'service-cards',
    slug: 'service-cards',
    name: 'Comprehensive Service Cards',
    category: 'Content & Layout',
    description:
      'Kartu penjelasan layanan bisnis mendalam yang mencakup deskripsi spesifikasi pekerjaan, industri sasaran, dan tautan eksplorasi lebih lanjut.',
    bestPractices: [
      'Sertakan pembeda visual antar layanan melalui kode warna atau icon spesifik',
      'Tautkan setiap kartu ke halaman detail layanan atau ke form inquiry langsung',
    ],
    useCases: [
      'Pemaparan bidang keahlian di website konsultan hukum atau akuntan',
      'Katalog divisi perbaikan di website bengkel atau kontraktor',
    ],
    compatibleWebsiteTypes: ['service-business', 'company-profile'],
    compatibleIndustries: ['law-firm', 'consultant', 'contractor', 'workshop'],
    relatedDesigns: ['professional-services', 'industrial'],
    seoTitle: 'Komponen Kartu Layanan & Jasa Spesialis',
    seoDescription: 'Komponen kartu penjelas layanan bisnis dengan penekanan pada solusi masalah dan kredibilitas tim pelaksana.',
    keyUXConsiderations: 'Jelaskan hasil nyata yang didapat klien, bukan sekadar istilah teknis internal yang membingungkan orang awam.',
  },
  {
    id: 'testimonial',
    slug: 'testimonial',
    name: 'Verified Testimonial & Review Spotlight',
    category: 'Trust & Proof',
    description:
      'Kartu kutipan ulasan klien nyata yang menampilkan foto profil, nama lengkap, jabatan, nama instansi, serta rating bintang kepuasan kerja.',
    bestPractices: [
      'Gunakan ulasan otentik yang menyebutkan pencapaian angka riil',
      'Hindari ulasan anonim atau foto stok palsu yang merusak kredibilitas institusi',
      'Cantumkan logo perusahaan klien jika memiliki izin resmi publikasi',
    ],
    useCases: [
      'Membangun rasa percaya di halaman beranda dan landing page penjualan',
      'Studi kasus kepuasan implementasi sistem pada website software house',
    ],
    compatibleWebsiteTypes: ['company-profile', 'landing-page', 'service-business', 'portfolio'],
    compatibleIndustries: ['consultant', 'saas', 'contractor', 'digital-agency'],
    relatedDesigns: ['modern-corporate', 'premium-corporate'],
    seoTitle: 'Komponen Ulasan Klien & Testimoni Terverifikasi',
    seoDescription: 'Komponen bukti sosial (social proof) terstruktur untuk membuktikan kepuasan dan rekam jejak kerja perusahaan.',
    keyUXConsiderations: 'Beri penekanan visual pada kalimat terpenting dalam kutipan agar pembaca kilat langsung menangkap intisari kepuasan.',
  },
  {
    id: 'faq',
    slug: 'faq',
    name: 'Semantic FAQ Accordion with Schema.org',
    category: 'Trust & Proof',
    description:
      'Accordion tanya jawab interaktif tanpa ketergantungan JavaScript berat, dibangun dengan semantic HTML <details> dan <summary> serta mikrodata Schema.org FAQPage.',
    bestPractices: [
      'Gunakan tag native <details> dan <summary> untuk aksesibilitas keyboard otomatis',
      'Sematkan script Schema.org FAQPage JSON-LD untuk memicu Google Rich Results',
      'Tuliskan pertanyaan persis seperti kalimat yang sering diajukan calon klien asli',
    ],
    useCases: [
      'Menjawab keraguan calon pembeli sebelum melakukan pemesanan',
      'Mendongkrak visibilitas SERP Google dengan accordion tanya jawab di hasil pencarian',
    ],
    compatibleWebsiteTypes: ['company-profile', 'landing-page', 'ecommerce', 'pricing-card'],
    compatibleIndustries: ['construction', 'law-firm', 'accounting', 'clinic'],
    relatedDesigns: ['minimal-business', 'modern-corporate'],
    seoTitle: 'Komponen FAQ Accordion Semantik dengan JSON-LD Google',
    seoDescription: 'Accordion FAQ zero-JS yang ramah Core Web Vitals dan langsung memicu tampilan kaya (rich snippet) pada Google Search.',
    keyUXConsiderations: 'Pertahankan teks jawaban tetap ringkas dan langsung ke pokok solusi tanpa kalimat berbelit-belit.',
  },
  {
    id: 'contact-section',
    slug: 'contact-section',
    name: 'Multi-Channel Contact & Location Map',
    category: 'Conversion & CTA',
    description:
      'Bagian kontak menyeluruh yang memadukan formulir pesan tervalidasi, nomor telepon kantor, alamat email resmi, jam operasional, dan peta interaktif Google Maps.',
    bestPractices: [
      'Lengkapi formulir dengan atribut autocomplete yang benar (name, email, tel)',
      'Sematkan peta Google Maps responsif yang membuka aplikasi peta saat disentuh di ponsel',
      'Sertakan nomor kontak alternatif darurat untuk layanan 24 jam',
    ],
    useCases: [
      'Halaman kontak resmi seluruh jenis website perusahaan',
      'Bagian bawah landing page untuk pengunjung yang lebih suka mengirim pesan tertulis',
    ],
    compatibleWebsiteTypes: ['company-profile', 'service-business', 'hotel', 'restaurant', 'school'],
    compatibleIndustries: ['hospital', 'clinic', 'construction', 'law-firm'],
    relatedDesigns: ['modern-corporate', 'industrial'],
    seoTitle: 'Komponen Kontak Kantor Resmi & Integrasi Google Maps',
    seoDescription: 'Komponen kontak multi-saluran terintegrasi validasi anti-spam dan koordinat peta Google Maps.',
    keyUXConsiderations: 'Beri indikator visual status sukses pengiriman yang jelas setelah formulir dikirimkan.',
  },
  {
    id: 'footer',
    slug: 'footer',
    name: 'Comprehensive Semantic Footer',
    category: 'Footers',
    description:
      'Bagian penutup situs semantik <footer> dengan ringkasan legalitas perusahaan, peta navigasi situs (sitemap links), legalitas privasi, hak cipta, dan kredensial hosting.',
    bestPractices: [
      'Kelompokkan tautan navigasi ke dalam kolom berkategori jelas',
      'Sertakan pernyataan hak cipta tahun berjalan yang dinamis',
      'Tampilkan rincian verifikasi keamanan (SSL HTTPS, edge compatible)',
    ],
    useCases: [
      'Penutup standar di seluruh halaman platform website',
      'Penyediaan tautan kepatuhan hukum (Kebijakan Privasi, Syarat & Ketentuan)',
    ],
    compatibleWebsiteTypes: ['company-profile', 'ecommerce', 'school', 'custom'],
    compatibleIndustries: ['finance', 'law-firm', 'manufacturing', 'logistics'],
    relatedDesigns: ['modern-corporate', 'minimal-business'],
    seoTitle: 'Komponen Footer Semantik & Struktur Internal Link',
    seoDescription: 'Arsitektur footer website standar korporat dengan pengelompokan tautan internal yang memperkuat PageRank SEO.',
    keyUXConsiderations: 'Pastikan warna teks tautan footer memiliki kontras yang nyaman dibaca di latar gelap.',
  },
  {
    id: 'portfolio-grid',
    slug: 'portfolio-grid',
    name: 'Categorized Portfolio & Case Study Grid',
    category: 'Content & Layout',
    description:
      'Grid pameran hasil karya dan proyek fisik dengan filter kategori interaktif, ringkasan nama klien, tahun pelaksanaan, dan thumbnail visual berkualitas tinggi.',
    bestPractices: [
      'Gunakan teknik lazy loading dan format WebP/AVIF untuk kompresi foto proyek',
      'Sediakan filter kategori tanpa perlu me-reload seluruh halaman browser',
      'Beri judul proyek yang deskriptif mengenai masalah yang dipecahkan',
    ],
    useCases: [
      'Pameran proyek bangunan di website kontraktor dan arsitek',
      'Galeri hasil renovasi interior dan workshop custom furniture',
    ],
    compatibleWebsiteTypes: ['portfolio', 'company-profile'],
    compatibleIndustries: ['architecture', 'interior-design', 'construction', 'digital-agency'],
    relatedDesigns: ['bold-creative', 'minimal-business'],
    seoTitle: 'Komponen Grid Portofolio & Studi Kasus Proyek',
    seoDescription: 'Tampilan grid proyek interaktif dengan filter kategori instan dan optimasi kompresi gambar otomatis.',
    keyUXConsiderations: 'Hindari teks overlay yang menutupi keseluruhan foto; tampilkan detail saat kursor menyentuh kartu (hover state).',
  },
  {
    id: 'gallery',
    slug: 'gallery',
    name: 'Interactive Photo Gallery & Lightbox',
    category: 'Content & Layout',
    description:
      'Koleksi galeri foto berkecepatan tinggi dengan kemampuan perbesaran gambar layar penuh (lightbox modal) dan navigasi geser ramah sentuhan jari.',
    bestPractices: [
      'Dukungan gesture swipe untuk pengguna layar sentuh smartphone',
      'Sertakan tombol tutup (close button) berukuran jelas dan tombol navigasi panah',
      'Selalu cantumkan atribut alt text pada setiap foto untuk indeks Google Image SEO',
    ],
    useCases: [
      'Galeri suasana kamar dan fasilitas pada website hotel dan villa',
      'Galeri foto hidangan dan suasana meja pada website restoran',
    ],
    compatibleWebsiteTypes: ['hotel', 'restaurant', 'portfolio'],
    compatibleIndustries: ['villa', 'hotel', 'restaurant', 'cafe'],
    relatedDesigns: ['minimal-business', 'restaurant'],
    seoTitle: 'Komponen Galeri Foto Interaktif & Lightbox Responsive',
    seoDescription: 'Komponen galeri visual modern dengan tampilan modal layar penuh dan kompresi cerdas untuk performa optimal.',
    keyUXConsiderations: 'Pastikan gambar resolusi penuh hanya dimuat saat pengunjung mengklik foto untuk menghemat kuota internet.',
  },
  {
    id: 'blog-layout',
    slug: 'blog-layout',
    name: 'Editorial Blog & Article Layout',
    category: 'Content & Layout',
    description:
      'Tata letak publikasi konten artikel edukasi dan wawasan industri dengan tipografi yang nyaman di mata, estimasi waktu baca, tanggal rilis, dan tombol bagikan.',
    bestPractices: [
      'Gunakan batas lebar kolom artikel maksimal 65-75 karakter per baris demi kenyamanan membaca',
      'Sertakan Schema.org Article atau BlogPosting untuk indeks artikel Google',
      'Sematkan modul artikel terkait di bagian bawah untuk menekan bounce rate',
    ],
    useCases: [
      'Strategi pemasaran konten organik (Content SEO)',
      'Publikasi berita kegiatan dan pengumuman di portal sekolah atau yayasan',
    ],
    compatibleWebsiteTypes: ['company-profile', 'school', 'service-business'],
    compatibleIndustries: ['law-firm', 'consultant', 'school', 'technology'],
    relatedDesigns: ['professional-services', 'minimal-business'],
    seoTitle: 'Komponen Layout Artikel Blog & Publikasi Konten SEO',
    seoDescription: 'Desain tipografi editorial artikel blog yang dioptimalkan untuk kenyamanan membaca berlama-lama dan peringkat SEO organik.',
    keyUXConsiderations: 'Pilih tinggi baris (line-height) 1.6 hingga 1.8 agar mata pembaca tidak lelah saat membaca artikel panjang.',
  },
  {
    id: 'team-section',
    slug: 'team-section',
    name: 'Leadership & Specialist Team Grid',
    category: 'Trust & Proof',
    description:
      'Kartu profil jajaran pimpinan direksi, dokter spesialis, atau partner hukum dengan foto potret formal, riwayat pendidikan, spesialisasi, dan tautan profil profesional.',
    bestPractices: [
      'Gunakan foto dengan sudut pencahayaan dan latar belakang yang senada antar anggota tim',
      'Cantumkan nomor izin registrasi profesi jika berkaitan dengan medis atau hukum',
    ],
    useCases: [
      'Profil advokat di website kantor hukum',
      'Jadwal dokter spesialis di website klinik kesehatan',
    ],
    compatibleWebsiteTypes: ['company-profile', 'service-business', 'school'],
    compatibleIndustries: ['law-firm', 'healthcare', 'consultant', 'clinic'],
    relatedDesigns: ['professional-services', 'premium-corporate'],
    seoTitle: 'Komponen Profil Tim Manajemen & Dokter Spesialis',
    seoDescription: 'Pameran kredensial tim ahli dan jajaran direksi untuk memperkuat otoritas keahlian dan transparansi institusi.',
    keyUXConsiderations: 'Tampilkan nama lengkap beserta gelar akademik secara rapi tanpa memotong teks.',
  },
  {
    id: 'statistics',
    slug: 'statistics',
    name: 'Metric Counter & Impact Statistics',
    category: 'Trust & Proof',
    description:
      'Baris angka pembuktian performa (misal: 100% On-Time Delivery, 500+ Proyek Selesai, 15 Tahun Pengalaman) dengan label penjelasan singkat di bawah tiap angka.',
    bestPractices: [
      'Gunakan hanya angka fakta riil yang dapat dipertanggungjawabkan kebenarannya',
      'Gunakan tipografi angka berukuran besar (bold display) yang kontras',
    ],
    useCases: [
      'Membuktikan skala produksi pada website pabrik manufaktur',
      'Membuktikan rekam jejak pada website kontraktor sipil dan logistik',
    ],
    compatibleWebsiteTypes: ['company-profile', 'landing-page', 'service-business'],
    compatibleIndustries: ['manufacturing', 'construction', 'logistics', 'finance'],
    relatedDesigns: ['industrial', 'modern-corporate'],
    seoTitle: 'Komponen Metrik Statistik & Pencapaian Bisnis',
    seoDescription: 'Komponen angka pencapaian terukur untuk membuktikan rekam jejak kredibilitas dan skala operasional perusahaan.',
    keyUXConsiderations: 'Beri label satuan yang jelas (Persen, Jam, Tahun, Unit) agar pembaca tidak salah menafsirkan angka.',
  },
  {
    id: 'timeline',
    slug: 'timeline',
    name: 'Work Process & Milestone Timeline',
    category: 'Content & Layout',
    description:
      'Visualisasi alur langkah kerja bertahap (Tahap 1 Konsultasi, Tahap 2 Perancangan, Tahap 3 Pelaksanaan, Tahap 4 Peluncuran) yang menghubungkan proses dari awal hingga selesai.',
    bestPractices: [
      'Gunakan garis penghubung visual antar titik tahapan',
      'Beri nomor urut yang jelas dan judul singkat pada setiap tahap',
    ],
    useCases: [
      'Menjelaskan alur pengerjaan website di halaman cara kerja',
      'Menjelaskan tahapan pembangunan fisik di website kontraktor',
    ],
    compatibleWebsiteTypes: ['company-profile', 'service-business', 'landing-page'],
    compatibleIndustries: ['contractor', 'consultant', 'architecture', 'software'],
    relatedDesigns: ['modern-corporate', 'minimal-business'],
    seoTitle: 'Komponen Timeline Alur Proses Kerja & Sejarah',
    seoDescription: 'Diagram tahapan kerja terstruktur untuk mengedukasi alur pelayanan yang transparan kepada calon klien.',
    keyUXConsiderations: 'Pada tampilan ponsel, susun timeline secara vertikal dari atas ke bawah agar mudah di-scroll.',
  },
  {
    id: 'comparison-table',
    slug: 'comparison-table',
    name: 'Feature & Competitor Comparison Table',
    category: 'Trust & Proof',
    description:
      'Tabel perbandingan mendalam yang menyandingkan fitur standar vs paket enterprise, atau membandingkan solusi Anda terhadap cara kerja tradisional yang lambat.',
    bestPractices: [
      'Pertahankan kolom header tabel tetap terbaca saat tabel digulir secara horizontal',
      'Gunakan simbol centang dan minus dengan warna kontras (hijau vs abu-abu)',
    ],
    useCases: [
      'Perbandingan paket website di halaman /website-packages',
      'Perbandingan produk software SaaS terhadap metode manual spreadsheet',
    ],
    compatibleWebsiteTypes: ['company-profile', 'service-business', 'custom'],
    compatibleIndustries: ['saas', 'software', 'technology', 'finance'],
    relatedDesigns: ['technology', 'modern-corporate'],
    seoTitle: 'Komponen Tabel Perbandingan Fitur & Layanan',
    seoDescription: 'Tabel komparasi matriks responsif yang memudahkan evaluasi keunggulan teknis antar opsi paket solusi.',
    keyUXConsiderations: 'Beri highlight latar belakang halus pada kolom produk yang paling Anda rekomendasikan.',
  },
  {
    id: 'logo-cloud',
    slug: 'logo-cloud',
    name: 'Client & Partner Trust Logo Cloud',
    category: 'Trust & Proof',
    description:
      'Deretan logo klien korporat, mitra vendor, atau sertifikasi industri dengan tampilan monokrom bersih yang tidak mencolok agar tetap selaras dengan desain website.',
    bestPractices: [
      'Ubah semua logo klien menjadi format monokrom (abu-abu/slate) agar terlihat rapi dan elegan',
      'Pastikan ukuran visual proporsional antar logo yang memiliki orientasi berbeda (persegi vs memanjang)',
    ],
    useCases: [
      'Ditempatkan tepat di bawah hero section untuk memicu rasa percaya instan',
      'Showcase mitra B2B pada website logistik dan manufaktur',
    ],
    compatibleWebsiteTypes: ['company-profile', 'landing-page', 'service-business'],
    compatibleIndustries: ['logistics', 'manufacturing', 'consultant', 'digital-agency'],
    relatedDesigns: ['modern-corporate', 'industrial', 'minimal-business'],
    seoTitle: 'Komponen Logo Cloud Mitra & Klien Terpercaya',
    seoDescription: 'Deretan logo klien korporat monokromatis untuk membuktikan validasi pasar dan reputasi industri.',
    keyUXConsiderations: 'Hindari logo bergerak terlalu cepat yang membuat mata lelah; prioritaskan tampilan statis yang stabil.',
  },
  {
    id: 'contact-form',
    slug: 'contact-form',
    name: 'Validated Lead Capture Contact Form',
    category: 'Forms & Inputs',
    description:
      'Formulir input pesan terproteksi spam bot dengan validasi tipe data (email, nomor WhatsApp, nama instansi) dan umpan balik status pengiriman.',
    bestPractices: [
      'Batasi jumlah kolom isian hanya pada informasi esensial untuk meminimalkan friksi pengguna',
      'Terapkan validasi input realtime saat pengguna selesai mengetik',
      'Sediakan proteksi bot menggunakan honeypot tersembunyi tanpa captcha membingungkan',
    ],
    useCases: [
      'Permintaan penawaran harga resmi (RFP)',
      'Konsultasi proyek baru pada halaman hubungi kami',
    ],
    compatibleWebsiteTypes: ['company-profile', 'service-business', 'landing-page', 'custom'],
    compatibleIndustries: ['construction', 'consultant', 'law-firm', 'accounting'],
    relatedDesigns: ['modern-corporate', 'professional-services'],
    seoTitle: 'Komponen Formulir Kontak & Lead Capture Validasi Anti-Bot',
    seoDescription: 'Formulir kontak modern dengan validasi input ramah pengguna dan proteksi spam tanpa mengorbankan kecepatan.',
    keyUXConsiderations: 'Beri fokus outline yang tegas saat kolom input aktif untuk membantu pengguna dengan keterbatasan visual.',
  },
  {
    id: 'whatsapp-cta',
    slug: 'whatsapp-cta',
    name: 'Floating & Inline WhatsApp CTA Button',
    category: 'Conversion & CTA',
    description:
      'Tombol kontak WhatsApp melayang (floating) dengan indikator status online dan pesan pembuka template yang otomatis menyesuaikan konteks halaman.',
    bestPractices: [
      'Gunakan warna hijau resmi WhatsApp (#25D366) yang langsung dikenali secara universal',
      'Format pesan URL encoded dengan konteks spesifik layanan yang sedang dibaca pengunjung',
      'Pastikan tombol melayang tidak menutupi tombol navigasi penting lainnya di layar ponsel',
    ],
    useCases: [
      'Saluran konversi utama pasar Indonesia di semua jenis website',
      'Bantuan cepat bagi pengunjung yang memiliki pertanyaan spesifik sebelum memesan',
    ],
    compatibleWebsiteTypes: ['company-profile', 'landing-page', 'ecommerce', 'restaurant', 'hotel', 'service-business'],
    compatibleIndustries: ['contractor', 'property', 'restaurant', 'workshop', 'retail'],
    relatedDesigns: ['modern-corporate', 'bold-creative', 'restaurant'],
    seoTitle: 'Komponen Tombol WhatsApp Floating & Form Direct Chat',
    seoDescription: 'Tombol aksi cepat WhatsApp terstandarisasi dengan pesan otomatis terstruktur untuk menutup penjualan instan.',
    keyUXConsiderations: 'Beri label teks pembantu seperti "Konsultasi Cepat" di samping icon agar pengguna paham fungsi tombol tersebut.',
  },
];
