import { WebsitePackage } from '@/types';

export const WEBSITE_PACKAGES: WebsitePackage[] = [
  {
    id: 'starter-umkm',
    slug: 'starter-umkm',
    tier: 'starter',
    name: {
      id: 'Paket Starter UMKM',
      en: 'Starter Business Package',
      ar: 'باقة المبتدئين والمشاريع الصغيرة',
    },
    tagline: {
      id: 'Solusi website resmi cepat & hemat untuk memulai kehadiran digital profesional',
      en: 'Fast, cost-effective professional website to launch your digital presence',
      ar: 'حل سريع واقتصادي لإطلاق موقعك الإلكتروني الرسمي',
    },
    idealFor: {
      id: 'Usaha mikro, toko fisik lokal, freelancer, dan produk dengan penawaran fokus',
      en: 'Small businesses, local stores, freelancers, and single product launches',
      ar: 'المشاريع الناشئة والمتاجر المحلية والمهنيين المستقلين',
    },
    basePrice: 1250000,
    turnaroundDays: 4,
    maxPages: 3,
    revisionCount: 2,
    includedFeatures: [
      'whatsapp',
      'contact-form',
      'maps',
      'seo-setup',
    ],
    highlights: [
      'Hingga 3 Halaman Utama (Beranda, Profil/Layanan, Kontak)',
      'Desain Responsif 100% Sempurna di HP, Tablet, Laptop',
      'Tombol WhatsApp Otomatis Langsung ke Chat Penjualan',
      'Formulir Pesan / Pertanyaan Terkirim ke Email',
      'Penyematan Titik Lokasi Google Maps Resmi',
      'Konfigurasi Standar SEO On-Page Google',
      'Gratis Setup SSL / HTTPS Keamanan Tingkat Tinggi',
      'Panduan Penggunaan Mandiri & Garansi Teknis 14 Hari',
    ],
  },
  {
    id: 'professional-business',
    slug: 'professional-business',
    tier: 'business',
    name: {
      id: 'Paket Professional Business',
      en: 'Professional Business Package',
      ar: 'باقة الشركات الاحترافية',
    },
    tagline: {
      id: 'Standar korporat lengkap dengan optimasi kecepatan tinggi dan kredibilitas maksimal',
      en: 'Full corporate standard with ultra-fast page speeds and maximum trust',
      ar: 'معايير مؤسسية متكاملة وسرعة فائقة لتعزيز موثوقية الشركة',
    },
    idealFor: {
      id: 'Perusahaan skala menengah, pabrik manufaktur, biro jasa, kontraktor, dan kantor profesional',
      en: 'Mid-sized companies, manufacturers, consultancies, and licensed service firms',
      ar: 'الشركات المتوسطة والمصانع ومكاتب الخدمات المهنية والمقاولات',
    },
    basePrice: 2850000,
    turnaroundDays: 8,
    maxPages: 8,
    revisionCount: 4,
    isPopular: true,
    includedFeatures: [
      'whatsapp',
      'contact-form',
      'maps',
      'seo-setup',
      'analytics',
      'gallery',
      'blog',
    ],
    highlights: [
      'Hingga 8 Halaman Lengkap (Beranda, Tentang, Layanan, Portofolio, Artikel, Kontak, dll)',
      'Pilihan Konsep Desain Sesuai Karakter Industri Anda',
      'Struktur Kode Ringan: Skor Waktu Muat Tinggi (Google Core Web Vitals)',
      'Schema.org JSON-LD Structured Data untuk Tampilan Hasil Pencarian Kaya (Rich Snippet)',
      'Setup Google Analytics 4 untuk Memantau Jumlah dan Perilaku Pengunjung',
      'Modul Galeri Portofolio Hasil Kerja / Foto Proyek dengan Lightbox',
      'Sistem Artikel / Berita untuk Strategi Pemasaran Konten',
      'Garansi Pemeliharaan Bug & Dukungan Prioritas 30 Hari',
    ],
  },
  {
    id: 'custom-enterprise',
    slug: 'custom-enterprise',
    tier: 'enterprise',
    name: {
      id: 'Paket Custom Enterprise',
      en: 'Enterprise Custom Solution',
      ar: 'باقة الحلول المخصصة للشركات الكبرى',
    },
    tagline: {
      id: 'Arsitektur bespoke skala besar dengan kapabilitas sistem kustom, multi-bahasa, atau integrasi API',
      en: 'Bespoke large-scale architecture with custom data logic, multilingual capability, or APIs',
      ar: 'بنية برمجية متقدمة تدعم تعدد اللغات وربط واجهات البرمجة والأنظمة المخصصة',
    },
    idealFor: {
      id: 'Holding company, platform e-commerce, institusi pendidikan, dan entitas dengan kebutuhan khusus',
      en: 'Corporate conglomerates, e-commerce storefronts, schools, and specialized web apps',
      ar: 'المجموعات القابضة والمتاجر الإلكترونية الكبرى والمؤسسات التعليمية',
    },
    basePrice: 6500000,
    turnaroundDays: 18,
    maxPages: 25,
    revisionCount: 'Unlimited',
    includedFeatures: [
      'whatsapp',
      'contact-form',
      'maps',
      'seo-setup',
      'analytics',
      'gallery',
      'blog',
      'booking',
      'payment-gateway',
      'multilingual',
      'admin-panel',
    ],
    highlights: [
      'Arsitektur Multi-Halaman Skalabilitas Tinggi (Hingga puluhan halaman)',
      'Kesiapan Struktur Multi-Bahasa (Indonesia, English, Arabic)',
      'Koneksi Payment Gateway Resmi (QRIS Otomatis, VA Bank, Kartu Kredit)',
      'Sistem Reservasi / Formulir Booking Dinamis dengan Notifikasi Real-time',
      'Panel Admin CMS untuk Pengelolaan Konten Mandiri yang Fleksibel',
      'Optimasi SEO Teknis Mendalam & Audit Aksesibilitas Web (WCAG)',
      'Dedicated Project Lead & Pendampingan Konsultasi Teknis',
      'Garansi Pemeliharaan Penuh & Dukungan Teknis 90 Hari',
    ],
  },
];
