import { WebsiteType } from '@/types';

export const WEBSITE_TYPES: WebsiteType[] = [
  {
    id: 'company-profile',
    slug: 'company-profile',
    name: {
      id: 'Company Profile',
      en: 'Company Profile',
      ar: 'ملف تعريفي للشركة',
    },
    tagline: {
      id: 'Membangun kredibilitas resmi dan profil korporat profesional',
      en: 'Build official corporate credibility and brand trust',
      ar: 'بناء المصداقية المؤسسية وثقة العلامة التجارية',
    },
    description: {
      id: 'Website multi-halaman untuk memperkenalkan visi, misi, legalitas, layanan, portfolio klien, dan kontak resmi institusi atau badan usaha.',
      en: 'Multi-page website presenting your vision, mission, services, portfolio, and contact details.',
      ar: 'موقع متعدد الصفحات يعرض رؤية الشركة، خدماتها، ومشاريعها.',
    },
    recommendedPages: 5,
    basePrice: 1800000,
    suitableIndustries: ['Korporat', 'Manufaktur', 'Konsultan', 'Logistik', 'Konstruksi'],
    featuresIncluded: ['whatsapp', 'contact-form', 'maps', 'seo-setup', 'analytics'],
    iconName: 'Building2',
  },
  {
    id: 'landing-page',
    slug: 'landing-page',
    name: {
      id: 'High-Converting Landing Page',
      en: 'Landing Page',
      ar: 'صفحة هبوط تسويقية',
    },
    tagline: {
      id: 'Fokus konversi cepat untuk kampanye iklan Google Ads & Meta Ads',
      en: 'Direct conversion focus for paid ads campaigns',
      ar: 'التركيز على التحويل المباشر للحملات الإعلانية',
    },
    description: {
      id: 'Halaman tunggal terstruktur dengan copywriting penjualan tajam, bukti sosial, penawaran terbatas, dan tombol aksi langsung ke WhatsApp atau registrasi.',
      en: 'Single conversion page engineered for marketing campaigns, lead collection, and direct WhatsApp sales.',
      ar: 'صفحة تسويقية واحدة مصممة لجمع العملاء المحتملين والتواصل عبر واتساب.',
    },
    recommendedPages: 1,
    basePrice: 950000,
    suitableIndustries: ['Produk Retail', 'Jasa Spesialis', 'Property', 'Webinar / Event', 'Peluncuran Produk'],
    featuresIncluded: ['whatsapp', 'contact-form', 'seo-setup', 'analytics'],
    iconName: 'Zap',
  },
  {
    id: 'ecommerce',
    slug: 'ecommerce',
    name: {
      id: 'Toko Online (E-Commerce)',
      en: 'E-Commerce Store',
      ar: 'متجر إلكتروني',
    },
    tagline: {
      id: 'Katalog produk digital dengan checkout otomatis dan sistem order',
      en: 'Product catalogue with cart, checkout, and direct ordering',
      ar: 'كتالوج المنتجات مع سلة الشراء والدفع المباشر',
    },
    description: {
      id: 'Platform penjualan digital lengkap dengan manajemen kategori produk, galeri varian, kalkulator ongkos kirim, dan integrasi order WhatsApp atau payment gateway.',
      en: 'Full digital storefront with product variations, cart, shipping calculations, and order notifications.',
      ar: 'منصة بيع رقمية متكاملة للمنتجات مع إدارة الطلبات وسلة التسوق.',
    },
    recommendedPages: 10,
    basePrice: 3500000,
    suitableIndustries: ['Fashion', 'Elektronik', 'Kuliner Kemasan', 'Beauty & Skincare', 'Kriya / Handicraft'],
    featuresIncluded: ['whatsapp', 'contact-form', 'seo-setup', 'analytics', 'payment-gateway', 'gallery'],
    iconName: 'ShoppingBag',
  },
  {
    id: 'restaurant',
    slug: 'restaurant',
    name: {
      id: 'Restoran & Cafe',
      en: 'Restaurant & Cafe',
      ar: 'مطعم ومقهى',
    },
    tagline: {
      id: 'Buku menu digital interaktif, visualisasi hidangan, dan reservasi meja',
      en: 'Interactive digital menu, food showcase, and table reservation',
      ar: 'قائمة طعام رقمية تفاعلية وحجز طاولات',
    },
    description: {
      id: 'Dirancang khusus untuk F&B dengan katalog menu berkategori, daftar harga terupdate, petunjuk lokasi terintegrasi Google Maps, dan tombol reservasi meja instan.',
      en: 'Tailored for F&B businesses with food menu cards, price lists, locations, and instant table reservations.',
      ar: 'مخصص للمطاعم والمقاهي مع عرض الأطباق والأسعار وخريطة الموقع.',
    },
    recommendedPages: 5,
    basePrice: 1750000,
    suitableIndustries: ['Restoran', 'Cafe & Coffee Shop', 'Catering', 'Bakery', 'Franchise Kuliner'],
    featuresIncluded: ['whatsapp', 'contact-form', 'maps', 'gallery', 'booking'],
    iconName: 'Utensils',
  },
  {
    id: 'hotel',
    slug: 'hotel',
    name: {
      id: 'Hotel & Villa Resort',
      en: 'Hotel & Villa Resort',
      ar: 'فندق وفيلا سياحية',
    },
    tagline: {
      id: 'Pamerkan kamar, fasilitas premium, dan sistem permohonan booking',
      en: 'Showcase suites, luxury facilities, and direct booking inquiries',
      ar: 'عرض الغرف والمرافق الفاخرة واستقبال طلبات الحجز',
    },
    description: {
      id: 'Website pariwisata & hospitality dengan galeri visual resolusi tinggi, spesifikasi tipe kamar, daftar fasilitas, aturan menginap, serta formulir inquiry reservasi.',
      en: 'Hospitality website featuring high-res photo galleries, room type details, amenity lists, and booking requests.',
      ar: 'موقع للضيافة مع صور عالية الدقة وتفاصيل الغرف ونماذج الحجز.',
    },
    recommendedPages: 8,
    basePrice: 2800000,
    suitableIndustries: ['Hotel', 'Villa', 'Resort', 'Homestay', 'Glamping'],
    featuresIncluded: ['whatsapp', 'contact-form', 'maps', 'gallery', 'booking', 'multilingual'],
    iconName: 'Hotel',
  },
  {
    id: 'school',
    slug: 'school',
    name: {
      id: 'Sekolah & Lembaga Edukasi',
      en: 'School & Academy',
      ar: 'مدرسة وأكاديمية تعليمية',
    },
    tagline: {
      id: 'Informasi akademik resmi, pendaftaran murid (PPDB), dan profil pengajar',
      en: 'Official academic portal, enrollment forms, and faculty profiles',
      ar: 'بوابة تعليمية رسمية واستمارات التسجيل وملفات المعلمين',
    },
    description: {
      id: 'Portal institusi pendidikan untuk mempublikasikan kurikulum, fasilitas kampus, prestasi, agenda kegiatan, pengumuman berkala, dan formulir pendaftaran daring.',
      en: 'Educational portal to showcase curricula, facilities, announcements, student achievements, and admissions.',
      ar: 'منصة للمؤسسات التعليمية لعرض المناهج والمرافق واستقبال طلبات القبول.',
    },
    recommendedPages: 10,
    basePrice: 2500000,
    suitableIndustries: ['Sekolah SD-SMA', 'Universitas / Kampus', 'Bimbel & Kursus', 'Pesantren', 'Training Center'],
    featuresIncluded: ['whatsapp', 'contact-form', 'maps', 'blog', 'seo-setup'],
    iconName: 'GraduationCap',
  },
  {
    id: 'portfolio',
    slug: 'portfolio',
    name: {
      id: 'Portfolio Personal / Agency',
      en: 'Portfolio & Creative',
      ar: 'معرض أعمال للمحترفين والوكالات',
    },
    tagline: {
      id: 'Tampilkan hasil karya terbaik, testimoni klien, dan layanan profesional',
      en: 'Highlight standout creative works, case studies, and client reviews',
      ar: 'إبراز أفضل الأعمال ودراسات الحالة وتقييمات العملاء',
    },
    description: {
      id: 'Website kurasi karya untuk desainer, fotografer, arsitek, agency kreatif, dan konsultan independen dengan layout visual yang memukau dan navigasi terarah.',
      en: 'Showcase platform for creators, designers, architects, and agencies with case studies and inquiry calls-to-action.',
      ar: 'موقع لعرض إبداعات المصممين والمهندسين والوكالات الإبداعية.',
    },
    recommendedPages: 5,
    basePrice: 1600000,
    suitableIndustries: ['Fotografi & Video', 'Arsitek & Desain Interior', 'Digital Agency', 'Freelancer', 'Artis & Seniman'],
    featuresIncluded: ['whatsapp', 'contact-form', 'gallery', 'seo-setup'],
    iconName: 'Palette',
  },
  {
    id: 'service-business',
    slug: 'service-business',
    name: {
      id: 'Jasa & Layanan Profesional',
      en: 'Service Business',
      ar: 'خدمات احترافية واستشارات',
    },
    tagline: {
      id: 'Penjelasan paket jasa spesifik dengan call-to-action konsultasi langsung',
      en: 'Transparent service packages with direct consultation calls-to-action',
      ar: 'تفاصيل الخدمات وحزم الأسعار مع استشارات مباشرة',
    },
    description: {
      id: 'Dikhususkan untuk penyedia jasa lokal maupun nasional: klinik hukum, akuntan, servis AC, logistik, kebersihan, perbaikan teknik, dan layanan spesialis lainnya.',
      en: 'Engineered for service providers: law firms, accountants, contractors, repairs, and consulting agencies.',
      ar: 'مخصص للشركات الخدمية مثل المكاتب القانونية والمحاسبية وخدمات الصيانة.',
    },
    recommendedPages: 5,
    basePrice: 1650000,
    suitableIndustries: ['Kantor Hukum', 'Akuntan Publik', 'Klinik Kesehatan', 'Servis Teknik', 'Kontraktor'],
    featuresIncluded: ['whatsapp', 'contact-form', 'maps', 'seo-setup', 'analytics'],
    iconName: 'Briefcase',
  },
  {
    id: 'custom',
    slug: 'custom',
    name: {
      id: 'Sistem Kustom / Web App',
      en: 'Custom Web Solution',
      ar: 'حلول برمجية مخصصة',
    },
    tagline: {
      id: 'Arsitektur bespoke sesuai proses bisnis spesifik dan integrasi API',
      en: 'Bespoke architecture built for complex workflow logic & APIs',
      ar: 'بنية برمجية مخصصة تلبي متطلبات الأعمال الدقيقة',
    },
    description: {
      id: 'Pengembangan web berskala khusus dengan alur database unik, sistem keanggotaan tertutup, integrasi API pihak ketiga, atau otomasi alur kerja internal.',
      en: 'Tailored web development for unique business models, bespoke workflows, authentication portals, and third-party APIs.',
      ar: 'تطوير برمجيات ومواقع مخصصة وفق النماذج التشغيلية الخاصة بك.',
    },
    recommendedPages: 15,
    basePrice: 5000000,
    suitableIndustries: ['Startup', 'Fintech', 'Marketplace', 'SaaS', 'Komunitas Khusus'],
    featuresIncluded: ['whatsapp', 'contact-form', 'seo-setup', 'analytics', 'admin-panel'],
    iconName: 'Code',
  },
];
