import { WebsiteType } from '@/types';

export const WEBSITE_TYPES: WebsiteType[] = [
  {
    id: 'company-profile',
    slug: 'company-profile',
    name: {
      id: 'Company Profile Perusahaan',
      en: 'Corporate Company Profile',
      ar: 'ملف تعريفي للشركة والمؤسسات',
    },
    tagline: {
      id: 'Membangun kredibilitas resmi, profil korporat, dan portofolio rekanan bisnis B2B',
      en: 'Build institutional trust, corporate presence, and B2B vendor qualification',
      ar: 'بناء المصداقية المؤسسية وعرض سابقة الأعمال للشركات',
    },
    description: {
      id: 'Website multi-halaman resmi institusi atau badan usaha (PT/CV) untuk memperkenalkan visi, misi, legalitas, susunan direksi, layanan utama, portofolio proyek klien, dan kontak kantor resmi.',
      en: 'Official multi-page website presenting your vision, leadership, services, past client projects, certifications, and headquarters contact.',
      ar: 'موقع مؤسسي متعدد الصفحات يعرض الرؤية، القيادة، الخدمات، وشهادات الجودة.',
    },
    overview: {
      id: 'Website Company Profile adalah jangkar identitas resmi bisnis Anda di ranah digital. Setiap kali calon klien, investor, atau tim pengadaan tender mencari nama perusahaan Anda di Google, website inilah yang menjadi bukti legalitas dan profesionalisme operasional Anda.',
      en: 'A corporate company profile website is the anchor of your business credibility, essential for tender verification and enterprise clients.',
      ar: 'الموقع التعريفي هو الركيزة الأساسية للثقة المؤسسية للمناقصات والشركاء التجاريين.',
    },
    recommendedPages: 6,
    basePrice: 1800000,
    suitableIndustries: ['construction', 'manufacturing', 'consultant', 'logistics', 'property'],
    featuresIncluded: ['whatsapp', 'contact-form', 'maps', 'seo-setup', 'analytics'],
    iconName: 'Building2',
    businessGoals: [
      'Memenuhi persyaratan verifikasi dokumen lelang & prakualifikasi tender B2B',
      'Meningkatkan kepercayaan investor, perbankan, dan mitra strategis',
      'Menampilkan portofolio hasil proyek dengan dokumentasi beresolusi tinggi',
      'Memudahkan pencarian kantor fisik perusahaan melalui Google Maps',
    ],
    benefits: [
      'Email bisnis resmi dengan domain sendiri (nama@perusahaan.com)',
      'Arsitektur loading ultra-cepat yang lolos uji Google Core Web Vitals',
      'Struktur data Schema.org Organization untuk indeks Google yang kaya',
      'Formulir permintaan proposal resmi (RFP) langsung ke email direksi',
    ],
    structureRecommendations: [
      { pageName: 'Beranda (Home)', description: 'Ringkasan nilai perusahaan, highlight layanan, metrik pencapaian, dan logo klien.' },
      { pageName: 'Tentang Kami (About Us)', description: 'Sejarah berdiri, visi & misi, struktur manajemen, dan sertifikat legalitas ISO/NIB.' },
      { pageName: 'Layanan / Produk', description: 'Rincian kapabilitas kerja, spesifikasi teknis, dan standar mutu pengerjaan.' },
      { pageName: 'Portofolio Proyek', description: 'Studi kasus proyek yang berhasil diselesaikan beserta foto lapangan.' },
      { pageName: 'Berita & Artikel', description: 'Aktivitas CSR perusahaan, pengumuman resmi, dan artikel edukasi industri.' },
      { pageName: 'Hubungi Kami (Contact)', description: 'Alamat kantor pusat/cabang, peta Google Maps, formulir pesan, dan nomor telepon.' },
    ],
    faqs: [
      {
        question: 'Apakah website company profile cocok untuk UMKM atau hanya PT besar?',
        answer: 'Sangat cocok untuk semua skala usaha. UMKM yang memiliki company profile resmi terbukti 4x lebih dipercaya oleh pembeli B2B dibanding yang hanya memiliki akun media sosial.',
      },
      {
        question: 'Bisakah ditambahkan tombol unduh Company Profile dalam bentuk file PDF?',
        answer: 'Tentu, kami menyematkan tombol unduh Company Profile PDF resmi yang siap dipresentasikan saat meeting klien.',
      },
    ],
    relatedIndustries: ['construction', 'manufacturing', 'logistics', 'consultant', 'law-firm'],
    relatedComponents: ['navbar', 'hero', 'service-cards', 'portfolio-grid', 'contact-section', 'footer'],
    recommendedDesigns: ['modern-corporate', 'premium-corporate', 'industrial'],
    recommendedPackage: 'professional-business',
    seoTitle: 'Jasa Pembuatan Website Company Profile Perusahaan Profesional',
    seoDescription: 'Bangun reputasi bisnis dengan website company profile modern. Desain kredibel, cepat, SEO-friendly, dan siap verifikasi tender B2B.',
    seoKeywords: ['website company profile', 'jasa buat web perusahaan', 'bikin company profile pt', 'web profil bisnis'],
  },
  {
    id: 'landing-page',
    slug: 'landing-page',
    name: {
      id: 'High-Converting Landing Page',
      en: 'High-Converting Landing Page',
      ar: 'صفحة هبوط تسويقية عالية التحويل',
    },
    tagline: {
      id: 'Fokus konversi cepat untuk kampanye iklan Google Ads, Meta Ads, dan TikTok Ads',
      en: 'Maximum conversion engineering for paid ads and targeted marketing campaigns',
      ar: 'مصممة خصيصاً للحملات الإعلانية الممولة والتحويل السريع للعملاء',
    },
    description: {
      id: 'Halaman tunggal terstruktur khusus dengan copywriting penjualan tajam (AIDA), bukti sosial (social proof), penawaran terbatas, dan tombol aksi langsung ke chat WhatsApp atau pendaftaran.',
      en: 'A high-converting single-page experience engineered for direct WhatsApp leads, registrations, or product sales from paid traffic.',
      ar: 'صفحة واحدة تركز على جمع بيانات العملاء أو التحويل المباشر لمحادثات واتساب.',
    },
    overview: {
      id: 'Landing Page adalah senjata utama pemasaran berbayar. Berbeda dari website korporat yang memiliki banyak menu cabang, landing page menghilangkan semua navigasi yang mendistraksi agar perhatian pengunjung 100% tertuju pada tawaran solusi Anda.',
      en: 'A landing page is engineered without distraction to guide paid ad visitors directly toward a single decisive call to action.',
      ar: 'صفحة بدون تشتيت تركز على عرض المشكلة والحل ودفع الزائر لاتخاذ قرار الشراء.',
    },
    recommendedPages: 1,
    basePrice: 950000,
    suitableIndustries: ['property', 'retail', 'course', 'beauty', 'fashion'],
    featuresIncluded: ['whatsapp', 'contact-form', 'seo-setup', 'analytics'],
    iconName: 'Zap',
    businessGoals: [
      'Menghasilkan lead prospek penjualan baru setiap hari dari iklan berbayar',
      'Mengurangi bounce rate dengan kecepatan muat instan di bawah 1 detik',
      'Menguji efektivitas penawaran produk atau promo tertentu (A/B testing ready)',
    ],
    benefits: [
      'Skor Google PageSpeed 95+ untuk memangkas biaya Cost Per Click (CPC) iklan',
      'Struktur copywriting psikologi konversi (Problem - Agitate - Solution - Offer)',
      'Floating CTA WhatsApp yang tetap terlihat saat pengunjung menggulir layar',
      'Integrasi tracking Meta Pixel & Google Ads Conversion API',
    ],
    structureRecommendations: [
      { pageName: 'Section Hero & Hook', description: 'Headline penangkap perhatian, visual produk utama, dan tombol aksi pertama.' },
      { pageName: 'Section Masalah & Rasa Sakit', description: 'Menguraikan kendala nyata yang sedang dihadapi audiens target.' },
      { pageName: 'Section Solusi & Fitur', description: 'Bagaimana penawaran Anda menuntaskan masalah secara tuntas dan cepat.' },
      { pageName: 'Section Bukti Sosial', description: 'Ulasan nyata pelanggan dan hasil sebelum-sesudah.' },
      { pageName: 'Section Penawaran Terbatas (Offer)', description: 'Bonus eksklusif, garansi uang kembali, dan harga promo.' },
      { pageName: 'Section Tombol Konversi WhatsApp', description: 'Call to action final dengan teks otomatis yang sudah terisi.' },
    ],
    faqs: [
      {
        question: 'Apakah landing page ini bisa dipasangi Google Tag Manager dan Meta Pixel?',
        answer: 'Tentu saja, kami memasangkan kode pelacakan Meta Pixel, Google Tag Manager, dan TikTok Pixel untuk melacak konversi secara akurat.',
      },
      {
        question: 'Seberapa cepat waktu pembuatan 1 landing page?',
        answer: 'Rata-rata selesai dalam 2-3 hari kerja setelah materi penawaran dan foto produk kami terima lengkap.',
      },
    ],
    relatedIndustries: ['property', 'course', 'fashion', 'beauty', 'retail'],
    relatedComponents: ['hero', 'cta', 'feature-grid', 'pricing-card', 'faq', 'whatsapp-cta'],
    recommendedDesigns: ['bold-creative', 'minimal-business', 'technology'],
    recommendedPackage: 'starter-umkm',
    seoTitle: 'Jasa Pembuatan Landing Page Penjualan Iklan Berkonversi Tinggi',
    seoDescription: 'Bikin landing page cepat loading & tinggi konversi untuk iklan Google & Meta Ads. Desain persuasif dan direct WhatsApp chat.',
    seoKeywords: ['jasa buat landing page', 'landing page iklan google', 'landing page konversi tinggi', 'web landing page murah'],
  },
  {
    id: 'ecommerce',
    slug: 'ecommerce',
    name: {
      id: 'Toko Online & E-Commerce',
      en: 'DTC E-Commerce Storefront',
      ar: 'المتجر الإلكتروني المتكامل',
    },
    tagline: {
      id: 'Katalog produk digital dengan checkout otomatis QRIS, VA Bank, dan sistem order',
      en: 'Full digital storefront with product variations, cart checkout, and payment gateways',
      ar: 'متجر بيع رقمي شامل لإدارة المنتجات وسلة الشراء والدفع التلقائي',
    },
    description: {
      id: 'Platform penjualan mandiri tanpa potongan komisi marketplace. Menampilkan manajemen kategori barang, varian ukuran/warna, kalkulator ongkir kurir, dan pembayaran terverifikasi otomatis.',
      en: 'Independent e-commerce storefront saving marketplace commission fees with real-time checkout and payment tracking.',
      ar: 'متجر مستقل بدون عمولات المنصات مع ربط بوابات الدفع الإلكتروني وحساب الشحن.',
    },
    overview: {
      id: 'Dengan memiliki toko online sendiri, brand Anda terbebas dari perang harga brutal di marketplace dan potongan biaya admin 10-15%. Anda menguasai 100% database pelanggan untuk strategi repeat order jangka panjang.',
      en: 'An independent storefront gives your brand customer data ownership, immune to marketplace policy changes.',
      ar: 'امتلاك متجرك الخاص يمنحك السيطرة على بيانات العملاء وتفادي حرب الأسعار والعمولات المرتفعة.',
    },
    recommendedPages: 10,
    basePrice: 3500000,
    suitableIndustries: ['ecommerce-industry', 'fashion', 'beauty', 'retail', 'automotive'],
    featuresIncluded: ['whatsapp', 'contact-form', 'seo-setup', 'analytics', 'payment-gateway', 'gallery'],
    iconName: 'ShoppingBag',
    businessGoals: [
      'Menjual produk 24 jam non-stop tanpa ketergantungan jam kerja admin kasir',
      'Menghemat margin laba dari potongan komisi platform e-commerce pihak ketiga',
      'Membangun loyalitas brand eksklusif di mata konsumen',
    ],
    benefits: [
      'Integrasi payment gateway resmi (QRIS instan, Virtual Account, Kartu Kredit)',
      'Katalog produk terstruktur dengan filter kategori dan pencarian instan',
      'Pilihan checkout cepat via WhatsApp atau payment gateway otomatis',
      'Tampilan mobile commerce super nyaman untuk jempol pembeli',
    ],
    structureRecommendations: [
      { pageName: 'Beranda Toko', description: 'Banner promo musiman, produk best seller, dan kategori unggulan.' },
      { pageName: 'Katalog Produk (Shop)', description: 'Daftar produk dengan filter harga, kategori, dan opsi urutan.' },
      { pageName: 'Detail Produk (Single Product)', description: 'Foto multi-angle, panduan ukuran, deskripsi bahan, dan tombol beli.' },
      { pageName: 'Keranjang & Checkout', description: 'Rincian belanja, input alamat, pilihan ekspedisi, dan opsi pembayaran.' },
      { pageName: 'Kebijakan Pengembalian & Garansi', description: 'Syarat retur barang rusak untuk membangun rasa aman berbelanja.' },
    ],
    faqs: [
      {
        question: 'Apakah ada potongan komisi dari setiap transaksi penjualan di website?',
        answer: 'Tidak ada potongan komisi dari kami sama sekali. Pendapatan penjualan 100% masuk ke rekening Anda.',
      },
    ],
    relatedIndustries: ['ecommerce-industry', 'fashion', 'beauty', 'retail'],
    relatedComponents: ['navbar', 'pricing-card', 'feature-grid', 'comparison-table', 'gallery', 'footer'],
    recommendedDesigns: ['ecommerce-retail', 'minimal-business'],
    recommendedPackage: 'professional-business',
    seoTitle: 'Jasa Pembuatan Website Toko Online E-Commerce Profesional',
    seoDescription: 'Bikin toko online resmi mandiri tanpa potongan marketplace. Checkout QRIS & VA otomatis, mobile friendly, dan siap scale-up.',
    seoKeywords: ['website toko online', 'jasa buat web olshop', 'bikin web ecommerce murah', 'toko online qris'],
  },
  {
    id: 'restaurant',
    slug: 'restaurant',
    name: {
      id: 'Restoran, Cafe & F&B',
      en: 'Restaurant & F&B Establishment',
      ar: 'المطاعم والمقاهي والضيافة',
    },
    tagline: {
      id: 'Buku menu digital interaktif, visualisasi hidangan lezat, dan reservasi meja instan',
      en: 'Interactive visual food menus, space atmosphere, and table reservations',
      ar: 'قوائم الطعام التفاعلية وعرض أجواء المكان وحجز الطاولات المسبق',
    },
    description: {
      id: 'Website khusus sektor kuliner dengan buku menu responsif tanpa unduh PDF berat, foto hidangan signature, integrasi Google Maps akurat, dan formulir booking meja acara.',
      en: 'Engineered for dining establishments with categorized mobile-first food cards, opening hours, and one-tap directions.',
      ar: 'موقع مصمم للمطاعم يعرض الأطباق وساعات العمل وحجز الموائد بنقرة واحدة.',
    },
    overview: {
      id: 'Pengunjung tempat makan modern selalu mencari daftar menu dan kisaran harga di internet sebelum melangkah keluar rumah. Website kuliner yang cepat dan menggugah selera langsung mengubah pencari info menjadi pengunjung meja.',
      en: 'Diners check online menus before visiting. A responsive digital menu drives foot traffic directly through your doors.',
      ar: 'يتصفح الزبائن قوائم الطعام والأسعار قبل الزيارة، مما يرفع الإقبال المباشر للمطعم.',
    },
    recommendedPages: 5,
    basePrice: 1750000,
    suitableIndustries: ['restaurant', 'cafe', 'catering', 'hotel'],
    featuresIncluded: ['whatsapp', 'contact-form', 'maps', 'gallery', 'booking'],
    iconName: 'Utensils',
    businessGoals: [
      'Memudahkan pelanggan membaca daftar menu tanpa unduh PDF yang menghabiskan kuota',
      'Menerima reservasi meja makan siang/malam keluarga dan corporate gathering',
      'Mengarahkan pengendara langsung ke titik parkir via navigasi Google Maps',
    ],
    benefits: [
      'Foto makanan resolusi tinggi terkompresi otomatis agar loading secepat kilat',
      'Kemudahan memperbarui harga atau menandai menu yang habis (sold out)',
      'Penyematan sertifikat Halal & ulasan bintang kepuasan pelanggan',
    ],
    structureRecommendations: [
      { pageName: 'Beranda', description: 'Atmosfer ruang makan, menu andalan chef, dan tombol reservasi meja.' },
      { pageName: 'Menu Digital', description: 'Kategori makanan utama, pembuka, hidangan penutup, dan minuman segar.' },
      { pageName: 'Reservasi Meja', description: 'Formulir tanggal, jam kedatangan, jumlah kursi, dan permintaan khusus.' },
      { pageName: 'Lokasi & Jam Buka', description: 'Peta interaktif, petunjuk parkir, dan kontak WhatsApp cabang.' },
    ],
    faqs: [
      {
        question: 'Apakah menu makanan bisa dibuka lewat scan QR Code di meja makan?',
        answer: 'Sangat bisa! Website menu digital ini sangat ideal dijadikan barcode scan di atas meja makan pelanggan Anda.',
      },
    ],
    relatedIndustries: ['restaurant', 'cafe', 'catering'],
    relatedComponents: ['navbar', 'hero', 'service-cards', 'gallery', 'contact-section', 'footer'],
    recommendedDesigns: ['restaurant', 'minimal-business'],
    recommendedPackage: 'starter-umkm',
    seoTitle: 'Jasa Pembuatan Website Restoran & Buku Menu Digital',
    seoDescription: 'Tingkatkan pengunjung restoran Anda dengan website menu makanan digital responsif, sistem booking meja, dan navigasi peta.',
    seoKeywords: ['website restoran', 'menu digital qr code', 'web kafe dan resto', 'jasa website kuliner'],
  },
  {
    id: 'hotel',
    slug: 'hotel',
    name: {
      id: 'Hotel, Villa & Hospitality',
      en: 'Hotel, Villa & Resort',
      ar: 'الفنادق والفلل والمنتجعات السياحية',
    },
    tagline: {
      id: 'Pamerkan kamar mewah, fasilitas private pool, dan penerimaan direct booking',
      en: 'Showcase luxury suites, leisure amenities, and commission-free direct booking',
      ar: 'عرض الأجنحة الفندقية والمسابح الخاصة وحجوزات الإقامة المباشرة',
    },
    description: {
      id: 'Website hospitality untuk hotel bintang, villa privat, dan resort wisata. Membantu mengurangi beban komisi OTA dengan sistem permohonan tanggal menginap langsung, paket liburan, dan galeri visual memukau.',
      en: 'Hospitality website built to drive direct room reservations, present suite specifications, and showcase amenities.',
      ar: 'موقع سياحي لجذب الحجوزات الفندقية المباشرة وتوفير عمولات المنصات الوسيطة.',
    },
    overview: {
      id: 'Komisi Online Travel Agent (OTA) memotong margin hotel 15% hingga 25%. Website resmi hotel dan villa memberikan saluran pemesanan langsung dengan tarif terbaik bagi tamu setia Anda.',
      en: 'Direct bookings protect profit margins from heavy OTA commissions while building a closer relationship with guests.',
      ar: 'الحجز المباشر عبر موقعك يوفر هوامش الربح المفقودة في عمولات وكالات السفر الإلكترونية.',
    },
    recommendedPages: 8,
    basePrice: 2800000,
    suitableIndustries: ['hotel', 'villa', 'tourism', 'travel'],
    featuresIncluded: ['whatsapp', 'contact-form', 'maps', 'gallery', 'booking', 'multilingual'],
    iconName: 'Hotel',
    businessGoals: [
      'Meningkatkan persentase pemesanan kamar langsung (direct booking)',
      'Menampilkan foto kamar resolusi tinggi dan fasilitas lengkap',
      'Mempromosikan paket meeting room perusahaan (MICE) dan paket wedding',
    ],
    benefits: [
      'Penyimpanan foto galeri berkecepatan tinggi tanpa kompromi kualitas',
      'Struktur siap multi-bahasa (Indonesia, English, Arabic)',
      'Tombol konfirmasi tanggal check-in langsung ke WhatsApp resepsionis',
    ],
    structureRecommendations: [
      { pageName: 'Beranda', description: 'Video atmosfer liburan, highlight kamar utama, dan tombol cek ketersediaan.' },
      { pageName: 'Akomodasi (Kamar & Villa)', description: 'Tipe kamar, ukuran ranjang, fasilitas mandi, dan pemandangan jendela.' },
      { pageName: 'Fasilitas & Layanan', description: 'Kolam renang, restoran internal, spa, pusat kebugaran, dan ruang meeting.' },
      { pageName: 'Destinasi Sekitar', description: 'Jarak tempuh ke objek wisata, pantai, dan bandara terdekat.' },
      { pageName: 'Kontak & Lokasi', description: 'Petunjuk rute navigasi dan formulir reservasi kamar.' },
    ],
    faqs: [
      {
        question: 'Dapatkah website menampilkan harga promo musiman (Peak Season / Low Season)?',
        answer: 'Bisa, tabel tarif menginap dapat diatur berdasarkan musim liburan atau promo akhir pekan.',
      },
    ],
    relatedIndustries: ['hotel', 'villa', 'travel', 'tourism'],
    relatedComponents: ['navbar', 'hero', 'gallery', 'feature-grid', 'contact-section', 'footer'],
    recommendedDesigns: ['premium-corporate', 'minimal-business'],
    recommendedPackage: 'professional-business',
    seoTitle: 'Jasa Pembuatan Website Hotel & Villa Direct Booking',
    seoDescription: 'Bikin website hotel & villa mewah untuk direct booking bebas potongan komisi. Galeri kamar estetik, reservasi online, dan multi-bahasa.',
    seoKeywords: ['website hotel', 'web villa bali', 'jasa website resort', 'direct booking hotel'],
  },
  {
    id: 'school',
    slug: 'school',
    name: {
      id: 'Sekolah, Kampus & Edukasi',
      en: 'School & Academic Portal',
      ar: 'المدارس والجامعات والمؤسسات الأكاديمية',
    },
    tagline: {
      id: 'Pusat informasi akademik resmi, pendaftaran murid/mahasiswa baru (PPDB/PMB), dan kurikulum',
      en: 'Official academic portal, faculty profiles, and online admissions system',
      ar: 'بوابة أكاديمية شاملة للمناهج وأعضاء التدريس والتسجيل الإلكتروني للطلاب',
    },
    description: {
      id: 'Portal institusi pendidikan formal maupun non-formal untuk mempublikasikan akreditasi, visi pendidikan, kurikulum belajar, prestasi siswa, fasilitas kampus, dan pendaftaran online terstruktur.',
      en: 'Comprehensive academic portal for schools, universities, and institutes detailing faculty curricula and admissions.',
      ar: 'بوابة تعليمية للمدارس والجامعات لعرض التخصصات والمرافق واستقبال طلبات القبول.',
    },
    overview: {
      id: 'Pendidikan adalah keputusan berbasis kepercayaan tertinggi dari orang tua. Website sekolah yang modern, rapi, dan transparan memberikan impresi pertama bahwa lembaga Anda dikelola secara profesional.',
      en: 'An academic portal reflects an institution\'s commitment to excellence and transparent communication with families.',
      ar: 'يعكس الموقع الاحترافي للمؤسسة التعليمية جودة التعليم والشفافية مع أولياء الأمور.',
    },
    recommendedPages: 10,
    basePrice: 2500000,
    suitableIndustries: ['school', 'university', 'training', 'course'],
    featuresIncluded: ['whatsapp', 'contact-form', 'maps', 'blog', 'seo-setup'],
    iconName: 'GraduationCap',
    businessGoals: [
      'Menjadi kanal utama pendaftaran murid baru saat musim PPDB',
      'Mendokumentasikan prestasi akademik, olimpiade, dan lomba siswa',
      'Menyajikan jadwal kalender akademik dan agenda kegiatan kampus',
    ],
    benefits: [
      'Formulir pendaftaran daring yang dapat diisi orang tua lewat ponsel',
      'Modul berita & artikel untuk publikasi karya ilmiah dan kegiatan ekstrakurikuler',
      'Keamanan hosting tinggi yang tahan lonjakan trafik saat pengumuman kelulusan',
    ],
    structureRecommendations: [
      { pageName: 'Beranda', description: 'Sambutan kepala sekolah/rektor, akreditasi resmi, dan highlight fasilitas.' },
      { pageName: 'Profil Lembaga', description: 'Sejarah, visi misi, jajaran pengajar berprestasi, dan legalitas izin dinas.' },
      { pageName: 'Kurikulum & Program', description: 'Struktur kurikulum nasional/internasional dan kegiatan minat bakat.' },
      { pageName: 'Pendaftaran (PPDB/PMB)', description: 'Jadwal gelombang tes, syarat administrasi, dan formulir daftar.' },
      { pageName: 'Fasilitas Kampus', description: 'Laboratorium komputer, perpustakaan, sarana olahraga, dan asrama.' },
    ],
    faqs: [
      {
        question: 'Apakah formulir PPDB online bisa diunduh oleh panitia dalam bentuk Excel?',
        answer: 'Ya, data pendaftaran dapat disalurkan langsung ke Google Sheets atau email resmi panitia pendaftaran.',
      },
    ],
    relatedIndustries: ['school', 'university', 'training', 'course'],
    relatedComponents: ['navbar', 'hero', 'feature-grid', 'blog-layout', 'contact-section', 'footer'],
    recommendedDesigns: ['training-education', 'modern-corporate'],
    recommendedPackage: 'professional-business',
    seoTitle: 'Jasa Pembuatan Website Sekolah & Portal Akademik Kampus',
    seoDescription: 'Bangun portal sekolah resmi terakreditasi dengan formulir PPDB online, direktori pengajar, kurikulum, dan galeri fasilitas.',
    seoKeywords: ['website sekolah resmi', 'web ppdb online', 'jasa website kampus', 'portal akademik sekolah'],
  },
  {
    id: 'portfolio',
    slug: 'portfolio',
    name: {
      id: 'Portofolio Personal & Agency Kreatif',
      en: 'Portfolio & Creative Studio',
      ar: 'معرض الأعمال الإبداعية والمصممين',
    },
    tagline: {
      id: 'Kurasi karya visual terbaik, studi kasus mendalam, dan penawaran jasa profesional',
      en: 'Highlight standout creative works, case studies, and bespoke client commissions',
      ar: 'استعراض المشاريع الإبداعية المتميزة وجذب عقود العمل المستقلة',
    },
    description: {
      id: 'Website pameran karya visual untuk fotografer, desainer interior, arsitek, studio animasi, dan agensi kreatif dengan tata letak minimalis dan navigasi elegan.',
      en: 'Visual showcase for creators, architects, and creative directors designed to highlight artistic nuance and project context.',
      ar: 'موقع لعرض إبداعات المصممين والفنانين والمهندسين مع التركيز على نقاء الصورة وسهولة التصفح.',
    },
    overview: {
      id: 'Karya visual membutuhkan panggung yang tidak bersaing dengan konten itu sendiri. Konsep portofolio kami menekankan whitespace bersih agar hasil karya Anda berbicara dengan sendirinya kepada calon klien bernilai tinggi.',
      en: 'Creative work requires an uncluttered canvas to let project quality speak directly to premium prospective clients.',
      ar: 'تحتاج الأعمال الإبداعية إلى مساحات نقية تبرز جودة التنفيذ والاهتمام بالتفاصيل.',
    },
    recommendedPages: 5,
    basePrice: 1600000,
    suitableIndustries: ['interior-design', 'architecture', 'digital-agency', 'marketing-agency'],
    featuresIncluded: ['whatsapp', 'contact-form', 'gallery', 'seo-setup'],
    iconName: 'Palette',
    businessGoals: [
      'Memikat calon klien yang mencari standar estetika visual tinggi',
      'Menjelaskan proses berpikir kreatif di balik setiap proyek (case study)',
      'Menjadi rujukan resmi link di profil Instagram, LinkedIn, atau bio media sosial',
    ],
    benefits: [
      'Galeri foto responsif dengan efek lightbox halus',
      'Kecepatan rendering tinggi meskipun memuat foto-foto resolusi besar',
      'Call to action kolaborasi yang terhubung langsung ke WhatsApp pribadi',
    ],
    structureRecommendations: [
      { pageName: 'Beranda / Grid Karya', description: 'Susunan kurasi proyek terbaik dengan filter kategori karya.' },
      { pageName: 'Detail Proyek (Case Study)', description: 'Latar belakang brief klien, eksplorasi konsep, dan hasil eksekusi akhir.' },
      { pageName: 'Tentang Creator / Studio', description: 'Filosofi berkarya, penghargaan yang pernah diraih, dan daftar klien.' },
      { pageName: 'Kontak Kolaborasi', description: 'Formulir inquiry proyek baru dengan perkiraan anggaran klien.' },
    ],
    faqs: [
      {
        question: 'Bisakah ditambahkan proteksi agar foto tidak mudah disalin sembarangan?',
        answer: 'Bisa, kami dapat menambahkan pencegahan klik kanan sederhana dan penandaan watermark visual pada foto.',
      },
    ],
    relatedIndustries: ['interior-design', 'architecture', 'digital-agency', 'marketing-agency'],
    relatedComponents: ['navbar', 'hero', 'portfolio-grid', 'gallery', 'contact-section', 'footer'],
    recommendedDesigns: ['bold-creative', 'minimal-business'],
    recommendedPackage: 'starter-umkm',
    seoTitle: 'Jasa Pembuatan Website Portofolio Kreatif & Arsitektur',
    seoDescription: 'Buat website portofolio estetis untuk desainer, arsitek, dan fotografer. Showcase karya visual berkelas dan lead inquiry proyek.',
    seoKeywords: ['website portofolio', 'web agency kreatif', 'jasa website arsitek', 'portfolio online profesional'],
  },
  {
    id: 'service-business',
    slug: 'service-business',
    name: {
      id: 'Jasa & Layanan Profesional',
      en: 'Professional & Technical Services',
      ar: 'الخدمات المهنية والاستشارية المتخصصة',
    },
    tagline: {
      id: 'Penjelasan spesifik paket jasa, estimasi biaya transparan, dan konsultasi cepat',
      en: 'Clear service packages, transparent cost structures, and instant inquiry booking',
      ar: 'باقات الخدمات المحددة والأسعار الشفافة وحجز الاستشارات المباشرة',
    },
    description: {
      id: 'Dikhususkan untuk kantor konsultan pajak, biro hukum, kantor akuntan, servis teknis, dan penyedia jasa spesialis lokal dengan call-to-action konsultasi langsung.',
      en: 'Built for service businesses requiring clear service breakdowns, certified trust badges, and direct consultation scheduling.',
      ar: 'مخصص للمكاتب الخدمية لتقديم تفاصيل الباقات وشروط التعاقد وحجز المواعيد.',
    },
    overview: {
      id: 'Bisnis jasa menjual rasa percaya dan kepastian solusi. Website yang memaparkan cakupan kerja secara transparan, rincian biaya yang jelas, dan profil keahlian yang terbukti akan memenangkan kepercayaan klien dibanding kompetitor.',
      en: 'Service businesses sell peace of mind. Transparent scope explanations and certified credibility win contracts.',
      ar: 'تعتمد الخدمات على الثقة، ويوفر الموقع الشفافية الكاملة في نطاق العمل والأسعار.',
    },
    recommendedPages: 5,
    basePrice: 1650000,
    suitableIndustries: ['consultant', 'law-firm', 'accounting', 'workshop', 'professional-services-industry'],
    featuresIncluded: ['whatsapp', 'contact-form', 'maps', 'seo-setup', 'analytics'],
    iconName: 'Briefcase',
    businessGoals: [
      'Menjelaskan ragam layanan secara detail agar calon klien paham solusinya',
      'Memfasilitasi janji temu konsultasi pertama (discovery call)',
      'Menampilkan ulasan dan rekomendasi dari klien korporat sebelumnya',
    ],
    benefits: [
      'Tata letak informasi yang mengarahkan pembaca langsung ke solusi masalahnya',
      'Integrasi tombol WhatsApp konsultasi darurat dan formulir pesan resmi',
      'Optimasi SEO lokal Google Maps agar mudah ditemukan klien sekitar',
    ],
    structureRecommendations: [
      { pageName: 'Beranda', description: 'Pernyataan keahlian utama, deretan masalah yang diselesaikan, dan CTA konsultasi.' },
      { pageName: 'Daftar Layanan & Paket', description: 'Rincian deliverable per layanan, cakupan tanggung jawab, dan estimasi biaya.' },
      { pageName: 'Tentang Tim & Legalitas', description: 'Sertifikasi profesi resmi dan rekam jejak pengalaman kerja.' },
      { pageName: 'Hubungi Kami', description: 'Formulir konsultasi, jadwal jam kerja, dan nomor WhatsApp spesialis.' },
    ],
    faqs: [
      {
        question: 'Apakah bisa dibuatkan formulir kalkulator perkiraan jasa sederhana?',
        answer: 'Bisa, calon klien dapat memilih jenis layanan yang dibutuhkan untuk melihat kisaran estimasi biaya.',
      },
    ],
    relatedIndustries: ['consultant', 'law-firm', 'accounting', 'professional-services-industry'],
    relatedComponents: ['navbar', 'service-cards', 'pricing-card', 'faq', 'contact-section', 'footer'],
    recommendedDesigns: ['professional-services', 'minimal-business'],
    recommendedPackage: 'professional-business',
    seoTitle: 'Jasa Pembuatan Website Kantor Jasa & Konsultan Profesional',
    seoDescription: 'Solusi website kantor jasa profesional. Transparansi cakupan layanan, sertifikasi keahlian teruji, dan booking konsultasi mudah.',
    seoKeywords: ['website kantor jasa', 'web konsultan profesional', 'jasa website kantor advokat', 'bikin web jasa'],
  },
  {
    id: 'custom',
    slug: 'custom',
    name: {
      id: 'Sistem Kustom & Solusi Web App',
      en: 'Custom Web Application',
      ar: 'الحلول البرمجية وتطبيقات الويب المخصصة',
    },
    tagline: {
      id: 'Arsitektur bespoke sesuai logika alur bisnis spesifik, portal keanggotaan, dan integrasi API',
      en: 'Bespoke software architecture engineered for complex business logic, portals, and APIs',
      ar: 'بنية برمجية مخصصة للعمليات المعقدة وبوابات العملاء وربط واجهات البرمجة',
    },
    description: {
      id: 'Pengembangan web berskala khusus dengan alur database unik, sistem portal keanggotaan tertutup, integrasi API perbankan/pihak ketiga, atau otomasi alur kerja internal korporat.',
      en: 'Engineered for bespoke operational platforms, member dashboards, complex business logic, and third-party API integrations.',
      ar: 'تطوير مواقع وتطبيقات مخصصة تلبي متطلبات الأعمال الفريدة وإدارة المستخدمين.',
    },
    overview: {
      id: 'Jika proses bisnis Anda tidak dapat diwadahi oleh CMS biasa, solusi web custom adalah jawabannya. Kami merancang arsitektur kode dari fondasi menggunakan framework modern berkinerja tinggi yang siap diskalakan ke jutaan pengguna.',
      en: 'When off-the-shelf templates cannot accommodate unique workflows, custom web architecture delivers bespoke scale.',
      ar: 'عندما لا تكفي القوالب الجاهزة لاحتياجاتك، نوفر لك بنية برمجية متطورة تلائم حجم أعمالك.',
    },
    recommendedPages: 15,
    basePrice: 5000000,
    suitableIndustries: ['saas', 'software', 'technology', 'finance', 'logistics'],
    featuresIncluded: ['whatsapp', 'contact-form', 'seo-setup', 'analytics', 'admin-panel'],
    iconName: 'Code',
    businessGoals: [
      'Mengotomasikan alur kerja manual perusahaan menjadi sistem digital terpusat',
      'Menyediakan portal login khusus karyawan, mitra, atau pelanggan',
      'Menghubungkan sistem web ke API pihak ketiga (ERP, payment gateway, kurir)',
    ],
    benefits: [
      'Kepemilikan penuh atas source code tanpa biaya lisensi platform bulanan',
      'Performa kode native yang tidak terbebani plugin lambat',
      'Skalabilitas infrastruktur yang siap menampung volume transaksi besar',
    ],
    structureRecommendations: [
      { pageName: 'Halaman Publik (Landing Pages)', description: 'Edukasi fitur sistem, keamanan enkripsi data, dan pendaftaran akun.' },
      { pageName: 'Portal Autentikasi', description: 'Alur Login, Registrasi, Lupa Password, dan Verifikasi Keamanan 2FA.' },
      { pageName: 'Dashboard Utama Sistem', description: 'Visualisasi metrik operasional, grafik transaksi, dan ringkasan aktivitas.' },
      { pageName: 'Manajemen Data & Laporan', description: 'Tabel data dengan ekspor file Excel/PDF dan filter multi-kolom.' },
    ],
    faqs: [
      {
        question: 'Apakah tim internal kami akan mendapatkan dokumentasi teknis kode?',
        answer: 'Ya, seluruh source code kami sertai dengan dokumentasi arsitektur, panduan deployment, dan repositori Git bersih.',
      },
    ],
    relatedIndustries: ['saas', 'software', 'technology', 'logistics'],
    relatedComponents: ['navbar', 'hero', 'feature-grid', 'pricing-card', 'contact-section', 'footer'],
    recommendedDesigns: ['technology', 'modern-corporate'],
    recommendedPackage: 'custom-enterprise',
    seoTitle: 'Jasa Pembuatan Web App Kustom & Sistem Portal Bisnis',
    seoDescription: 'Kembangkan sistem web app kustom berkinerja tinggi. Arsitektur bespoke modern, aman, skalabel, dan terintegrasi API bisnis Anda.',
    seoKeywords: ['jasa buat web app', 'custom web development', 'bikin sistem portal bisnis', 'web aplikasi custom'],
  },
];
